site_name: Nishant's Notes
theme:
  name: mkdocs
  color_mode: dark
  highlightjs: true
nav:
  - Home: 'index.md'
  - CppPrimer:
      - 'Chapter 1': 'cppprimer/ch01.md'
      - 'Chapter 2': 'cppprimer/ch02.md'
